[package]
name = "sql_fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.6.1", features = ["integer"] }
sqlparser = "0.45.0"
csv = "1.3.0"
duckdb = { version = "0.10.2", features = ["bundled"] }
rayon = "1.10.0"

[features]
multi_bit_pbs = []
